<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<div>

<h3>A DMCA Takedown is:</h3>
<p>
When content is removed from a website at the request of the owner of the content or the owner of the copyright of the content. It is a well established, accepted, internet standard followed by website owners and internet service providers.

Your right to process. Any owner of content has the right to process a takedown notice against a website owner and/or an Online Service Provider (e.g. ISP, hosting company etc.) if the content owner's property is found online without their permission.
</p>

<p>Click <a href="http://www.dmca.com/signup/default.aspx?ref=sol08a2">here</a> to Start Your Takedown</p>
cont.
<p>
Note: although the DMCA is part of US Copyright law, a DMCA Takedown does not require the content to be copyrighted in order to process the takedown and for the content to be taken down by the website owner or OSP.
In other words,the fact the content is yours, or in the case of a photo or video the subject is you, can be sufficient enough to request a takedown AND for the content to be taken down.
Click here to process a takedown now:<a href="http://www.dmca.com/signup/default.aspx?ref=sol08a2"> Website Takedown Form </a>
This is a list of takedown conditions:
</p>
<p>
when copyright infringing content is removed or "taken down" from a website, by the website owner, upon receipt of a DMCA Takedown Notice from their ISP / Hosting company. This notice is generated by the, or on behalf of, the illegally published content owner, distributor, publisher etc.
when copyright infringing content is removed or "taken down" from a website by the website owner upon receipt of a DMCA Takedown Notice from the, or on behalf of, the content owner,distributor, publisher etc.
when copyright infringing content is removed or "taken down" from a website by the by the ISP or Hosting company of the website that is publishing the infringing content. This occurs because the website owner has not voluntarily complied with a DMCA Notice and the ISP or Hosting company must comply with the Takedown notice.
when an infringing website is taken down or "offline" by it's ISP or Hosting company. This occurs because the website owner does not voluntarily comply with a Takedown notice as described above.
These Takedown actions occur upon receipt of a DMCA Takedown Notice which uses stipulations laid out in the Digital Millennium Copyright Act. (DMCA). This Act directly addresses the take down of (copyright) infringed content from a website which is publishing content in violation of copyright protection act or content being used without permission or not in accordance to the sworn statement of the content owner.
</p>
</div>

</body>
</html>